version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: wizard-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: wizard_app
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - wizard-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wizard-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - MONGODB_URI=mongodb://mongodb:27017/wizard_app
      - PORT=3001
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - wizard-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wizard-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - wizard-network

networks:
  wizard-network:
    driver: bridge

volumes:
  mongodb_data:
